/**
 * WS Event Handler Constants
 */

export const HANDLER_CONNECTION = 'CONNECTION';
export const HANDLER_ROOM = {
  ROOM: 'ROOM',
  LIST: 'ROOM/LIST',
  CREATE_ROOM: 'ROOM/CREATE_ROOM',
  JOIN_ROOM: 'ROOM/JOIN_ROOM',
  LEAVE_ROOM: 'ROOM/LEAVE_ROOM',
};
export const HANDLER_CHAT = {
  CHAT: 'CHAT',
  SEND_ROOM_CHAT_MESSAGE: 'CHAT/SEND_ROOM_CHAT_MESSAGE',
};

export const MESSAGE_NEW_ROOM_MEMBER_JOINED = 'MESSAGE_NEW_ROOM_MEMBER_JOINED';
export const MESSAGE_ROOM_MEMBER_LEAVED = 'MESSAGE_ROOM_MEMBER_LEAVED';
